language: python
python:
  # - "3.7"
  - "3.8"

install:
  - pip install astropy
  - pip install cobaya
  - pip install camb
  - git clone https://github.com/lesgourg/class_public
  - cd class_public
  - make
  - pip install git+https://github.com/simonsobs/lat_mflike
  - python setup.py install
script:
  - pytest -vv

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
