dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install astropy
  - pip install git+https://github.com/simonsobs/lat_mflike
  - python setup.py install
script:
  - pytest -vv
