language: python
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gfortran
before_install:
  - gfortran --version  
  - pip install astropy
  - pip install cobaya
  - pip install camb
  - pip install cython
  - export CWD=`pwd`
  - cd ..
  - git clone https://github.com/lesgourg/class_public
  - cd class_public
  - make
  - cd ..
  - git clone https://github.com/simonsobs/lat_mflike
  - cd lat_mflike
  - pip install .
  - cd tests
  - cobaya-install test_mflike_sacc.yaml
  - cd $CWD
install:
  - pip install .
script:
  - python -c 'import solike; print(solike)'
  - python -c 'import classy; print(classy)'
  - pytest -vv .
