language: python
python:
  # - "3.7"
  - "3.8"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt update  
  - sudo apt-get -y install gcc-9

install:
  - pip install astropy
  - pip install cobaya
  - pip install camb
  - git clone https://github.com/lesgourg/class_public
  - cd class_public
  - make
  - pip install git+https://github.com/simonsobs/lat_mflike
  - python setup.py install
script:
  - pytest -vv
