language: python
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gfortran
before_install:
  - gfortran --version  
install:
  - pip install astropy
  - pip install cobaya
  - pip install camb
  - pip install cython
  - export CWD=`pwd`
  - cd ..
  - git clone https://github.com/lesgourg/class_public
  - cd class_public
  - make
  - cd $CWD
  - pip install git+https://github.com/simonsobs/lat_mflike
  - pip install .
script:
  - cd tests
  - pytest -vv .
