language: python
python:
  -"3.8"
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gfortran
before_install:
  - gfortran --version
install:
  - pip install astropy
  - pip install cobaya
  - pip install camb
  - pip install cython
  - git clone https://github.com/lesgourg/class_public
  - cd class_public
  - make
  - cd ..
  - pip install git+https://github.com/simonsobs/lat_mflike
  - python setup.py install
script:
  - pytest -vv
