name: Testing

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.py }}
        channels: conda-forge,defaults
        channel-priority: strict
        show-channel-urls: true

    - name: install ccl
      run: | 
        conda install pyccl

    # - name: install deps
    #   run: |
    #     conda install \
    #       pip \
    #       numpy nose coveralls flake8 pyyaml gsl fftw cmake swig scipy \
    #       compilers pkg-config setuptools_scm pytest pandas pytest-cov \
    #       cython "camb>=1" isitgr traitlets fast-pt
    #     # if [[ ${MATRIX_OS} == "macos-latest" ]]; then
    #     #   conda install llvm-openmp
    #     #   echo "DYLD_FALLBACK_LIBRARY_PATH=${CONDA_PREFIX}/lib" >> $GITHUB_ENV
    #     #   SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
    #     #   echo "SDKROOT: ${SDKROOT}"
    #     #   echo "SDKROOT=${SDKROOT}" >> $GITHUB_ENV
    #     #   echo "CONDA_BUILD_SYSROOT=${SDKROOT}" >> $GITHUB_ENV
    #     fi
    #   env:
    #     MATRIX_OS: ${{ matrix.os }}

    - name: Install camb
      run: |
        conda install camb

    # - name: Install classy
    #   run: |
    #     conda install cython
    #     git clone https://github.com/lesgourg/class_public
    #     cd class_public
    #     make
    #     cd ..

    - name: Unit tests
      run: |
        pip install camb
        pip install pytest
        pytest -vv soliket
